### PR TITLE
nitdoc: display source code using nitlight

### LINKED ISSUE #953: Associate nitdoc and nitlight
nitdoc should be able to go to nitlight generated files (hightlighted source code).

nitlight metadata (clicking on identifiers) should be able to points nitdoc pages.

### PR DESCRIPTION
**Pull request by Morriar**
This PR introduces pages for module source using nitlight.
Links to source code are no redirected to these pages.
While MModule pages point to the begining of the page, MClasse and MProperty page points to anchored lines.

Fixes #953

Every good thing as a cost, +1 sec on `standard/` generation:

image

If the overhead is not acceptable, one can use `--no-code` to disable this feature.
The option `--source` stills work with nitdoc but produces a warning if not used in conjunction with `--no-code`.

Commits before ac498bc belong to #1446, please disregard.

### CODE REVIEW

**Comment by R4PaSs** [comment]
:shipit:

**Comment by Morriar** [comment]
Demo is up!

Example of source code page generated by nitdoc: from the burger menu of [Array](http://moz-code.org/demos/nitdoc-code/stdlib/module_standard__collection__array.html) > [View source](http://moz-code.org/demos/nitdoc-code/stdlib/code_module_standard__collection__array.html).

Also, every property can be linked directly to the code. For example the link [Array::to_s](http://moz-code.org/demos/nitdoc-code/stdlib/class_standard__collection__array__Array.html#buffered_ropes-__Array__to_s.definition) > [View source](http://moz-code.org/demos/nitdoc-code/stdlib/code_module_buffered_ropes-.html#L307) points directly to the [line 307](http://moz-code.org/demos/nitdoc-code/stdlib/code_module_buffered_ropes-.html#L307)

**Comment by privat** [comment]
drop-down seems broken in the generated source. raw html is displayed in popub boxes instead of formatted things

**Comment by privat** [comment]
keeping a link to navigate in the version-controlled source might still be useful because it provide vcs information and capabilities (ie the github infrastructure for instance)

**Comment by privat** [comment]
maybe look at `HighlightVisitor::foot_content` for the issue with popup things

**Comment by privat** [comment]
For information, highlight crashes if you try to process `lib/pthreads/examples/threaded_example.nit`. Does using it with nitdoc works?

**Comment by Morriar** [comment]
@privat it should be fixed by 43938fbf6

**Comment by Morriar** [comment]
reroll: keep option --source for github link

Updated the demo. Please note that github link still look broken because of the local git revision used instead of master.

**Comment by privat** [comment]
+1

**Comment by privat** [comment]
I am not entirely sure it is related to this PR but nitdoc on the full source code is taking 6GB of ram and need more that 4h of CPU time. I'm tempted to assume that is it is far too much so I just killed it on the big tests.

**Comment by Morriar** [comment]
It can be related. I will investigate.

**Comment by privat** [comment]
There was memory improvement in hightlight and libhtml. Maybe you could rebase and recheck

**Comment by Morriar** [comment]
Reroll: Let's see about perfs

**Pull request closed without merging**
