### PR TITLE
Abstract_text: Add a method to get string representation of float in scientific notation

### PR DESCRIPTION
**Pull request by Delja**
Add a method `to_se` to get the string representation of float in scientific notation.
```
123.45.to_se == "1.2345e+02"
0.001234.to_se  == "1.234e-03"
10860460000.0.to_se == "1.086046e+10"
```
The to_se method have a precision between 1 to 6 max decimal. The precision is adapted in function of the number.

Add a `to_precision_size_with_format` and `to_precision_fill_with_format` method to get the representation in a specific given format

### CODE REVIEW

**Comment by Delja** [comment]
To my knowledge, there is no language that specifically provides a method for returning a string with scientific notation. Generally the conversion is done using a user-specified format. The best solution would be to define a more verbose name. Example `to_s_expo_notation` or something else.

**Comment by Morriar** [comment]
https://python-reference.readthedocs.io/en/latest/docs/float/scientific.html

**Comment by Delja** [comment]
@Morriar Your link it's for returns a float multiplied by the specified power. The objective of this pr is to provide a method to return a string representing a float in a scientific notation.

**Comment by R4PaSs** [comment]
May I suggest something like `to_sci` for the name? Bit more concise than `to_scientific_notation`, and slightly more explicit than `to_se` in my eyes

**Comment by Delja** [comment]
@R4PaSs nice, the `to_sci` look good, but `to_scientific_notation` it's also correct.
@privat what do you prefers?

**Comment by privat** [comment]
+0.1e1 for `to_sci`

**Pull request merged**
