### PR TITLE
Add trails to nitiwiki

### PR DESCRIPTION
**Pull request by privat**
Wikilinks, with the directive `trail`, will register the target page as an element of a trail.
Each `trail` are chained together and will display navigational link `prev` for the previous page of the trail, `next` for the next page of the trail and `up` to go to the pages that has used the `trail` wikilink.

For instance, if the page `doc.md` has the following content:

~~~md
To use nitiwiki, first [[trail: install|install it]],
then [[trail: simple_wiki|create a first wiki]].

You can also do advanced things like:

* [[trail: github|editing pages with github]]
* [[trail: templating| adapting the templates]]
~~~

A trail will be made and will consist of the sequence of pages `install`, `simple_wiki`, `github` and `templating`.
On each one of these pages, there will be links for the previous, the next page and the `doc.md` pae.

If a page includes trail wikilinks and is also the target for trail wikilinks, then the two trails are merged and pages will be visitable in a depth-first order.
This nesting of trails can be used to have sections and sub-sections.

Demo is up: http://info.uqam.ca/~privat/nitlanguage/manual/

### CODE REVIEW

**Comment by Morriar** [comment]
No documentation about it in the README?

To be honest, I don't undestand how to use it. You juste have to use the trail directive and everything is done for you?

**Comment by privat** [comment]
reroll:

* do not force whitespace after command in wikilink
* update README about trails
* add trails in examples

**Comment by Morriar** [comment]
+1

**Comment by R4PaSs** [comment]
:shipit:

**Comment by privat** [comment]
reroll: spell in the README

**Pull request merged**
