### PR TITLE
nitweb: show metrics

### PR DESCRIPTION
**Pull request by Morriar**
This PR introduce the metrics displaying in nitweb.

For now, only classes and modules metrics are shown (mclass_metrics.nit, mmodules_metrics.nit, inheritance_metrics.nit).

Some examples (may be long to load on my little server):
* [core::Array](http://nitweb.moz-code.org/doc/core::Array)
* [core::array](http://nitweb.moz-code.org/doc/core::array)
* [core>collection>](http://nitweb.moz-code.org/doc/core%3Ecollection%3E)
* [core](http://nitweb.moz-code.org/doc/core)

### CODE REVIEW

**Comment by privat** [comment]
~~~
503: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN"> <html><head> <title>503 Service Unavailable</title> </head><body> <h1>Service Unavailable</h1> <p>The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later.</p> <hr> <address>Apache/2.4.7 (Ubuntu) Server at nitweb.moz-code.org Port 80</address> </body></html>
~~~

Else +1

**Comment by privat** [comment]
ping?

**Comment by jcbrinfo** [comment]
* D3 pies are cute
* Nice refactoring of class and module metrics
:+1: +1

**Comment by jcbrinfo** [comment]
Nitpicking: When percentages are below 10 %, they are unreadable on the small pie charts. In this case, can you put them in the label instead of over the chart?

**Pull request merged**
