### PR TITLE
Promote location in MEntity

### PR DESCRIPTION
**Pull request by privat**
For some unknown historical reasons, the location was only provided to some specific model entities. By extending it to all entities, this simplify clients that need to process, visit or filter entities.

Location is not nullable for all entities. This is simpler but need some place-holder object for fictive location. ie some location objects that mean "no location".

### CODE REVIEW

**Comment by privat** [comment]
ping @xymus and @Morriar for the API issue.

**Comment by privat** [comment]
test this please

**Comment by privat** [comment]
test this please

**Comment by Morriar** [comment]
+1 for the not nullable + placeholder

**Comment by privat** [comment]
reroll: solve conflicts and location is not nullable

**Pull request merged**
