### PR TITLE
Faster hex parsing

### PR DESCRIPTION
**Pull request by R4PaSs**
As said in #1895, we need faster parsing of UTF-16 escaping sequences, this PR is the answer.

It makes the runtime of the `large_escaped` benchmark go down from ~5s to ~3.5s, and with valgrind, from 26GIr to 20GIr

Note: based on #1886, only the 4 last commits are of interest here

### CODE REVIEW

**Comment by privat** [comment]
seems good.

**Comment by privat** [comment]
plase rebase on master

**Comment by R4PaSs** [comment]
Reroll: Rebased on master to have only hexdigit-related performance improvements

**Comment by R4PaSs** [comment]
Reroll: fixed the OOB problem in `FlatText::to_hex`

**Pull request merged**
