### PR TITLE
serialization: serialize the Error class and avoid  abstract classes with factories

### PR DESCRIPTION
**Pull request by xymus**
This PR implements the serialization of the `Error` class manually, it is declared in `core` above the `serialization` module.

Also updates `nitserial` so that it does not attempt to instantiate abstract classes with factories.

@privat I have doubts about the use of `is_abstract` and `is_class`, is it appropriate?

### CODE REVIEW

**Comment by privat** [comment]
why a manual serialization or Error is necessary?

about your doubts, if you just want to filter only concrete class then something like `if mtype.mclass.kind == concrete_kind then ...` should be enough

**Comment by xymus** [comment]
The `serialize` annotation is unknown in `core`, so it can't be used there... Do you think that we could define the `serialize` annotation with the other annotations (in `core` or in the `compiler`) and only activate the phase if the `Serializable` class exists?

**Comment by xymus** [comment]
Rerolled to use `mtype.mclass.kind == concrete_kind`.

**Comment by privat** [comment]
I'm fine with the manually defined serialization, I just wanted a `why` and I got one.
From a tool/language robustness POV, I think it is better to reduce dependencies between core components, so I am fine with it.

**Comment by privat** [comment]
+1

**Pull request merged**
