### PR TITLE
hightlight as a service

### PR DESCRIPTION
**Pull request by privat**
Some small adaptation to make the various tools less command-line dependent.

As a proof a concept, there is a simple nitlight&nitpick online tools.
Maybe a future nit online validador (nitltn?)

http://pratchett.info.uqam.ca:8081/

It seems that the machine is no more accessible from outside :/

### CODE REVIEW

**Comment by Morriar** [comment]
image

I suggest to put the code under the form, so tooltips will not be cropped by the page.

**Comment by privat** [comment]
the tooltips of nitlight are just crappy anyway. This one contains only a dropbox with a badly-wrapped and unreadable message. It is why I repeat the messages bellow in a ul in fact.

If someone have a better proposal for popups in nitlight I will gladly take them.
I can still switch the two parts if you prefer

**Comment by privat** [comment]
reroll: switch textarea and result; try to pass tests

**Comment by Morriar** [comment]
+1

**Pull request merged**
