### PR TITLE
Intro partial implementation of app::UI for iOS

### PR DESCRIPTION
**Pull request by xymus**
This PR intro the support for portable graphical applications on the iOS platform. With enough features to compile and run the calculator example. 

The most notable app UI features supported under iOS are buttons, labels, text fields and layouts. More work is needed for list views and for other abstractions such as `http_request` and `data_store`.

This required some fixes to the compiler when targeting iOS as well as updates for the latest version of Xcode. And some more documentation for both iOS and OS X.

---

As usual, I left some commented out code generated by objcwrapper for future use when all the needed types are available.

### CODE REVIEW

**Comment by R4PaSs** [comment]
Objective-C is as ugly as it is batshit insane.
But let's give a :shipit: to this :hankey:

**Comment by xymus** [comment]
please test this

**Comment by xymus** [comment]
ok to test

**Comment by privat** [comment]
+1

**Comment by privat** [comment]
I'm not sure if I really can safely merge it since http://gresil.org/jenkins/view/Int%C3%A9gration/job/CI%20Github%20OSX/ is still out of order

**Comment by xymus** [comment]
please test osx

**Pull request merged**
