### PR TITLE
lib/core: Renamed `Text::bytelen` to `Text::byte_length`

### PR DESCRIPTION
**Pull request by R4PaSs**
As one famous man once said: "Je vous ai compris!".

So, I understood that some of us (@xymus, @ppepos, @BlackMinou, etc.) did not like the `bytelen` name, since it was not that explicit.
Well, its days are numbered and it is replaced by the longer but more explicit `byte_length`.

### CODE REVIEW

**Comment by ppepos** [comment]
``` asm
inc eax
ret
```

**Comment by privat** [comment]
+1

**Comment by xymus** [comment]
+1 !

**Comment by jcbrinfo** [comment]
:shipit: +1

**Pull request merged**
