### PR TITLE
src/model: fix mdoc_or_fallback for MClasses and MProperties

### PR DESCRIPTION
**Pull request by Morriar**
Specify `mdoc_or_fallback` behavior in MClass and MProperty (return intro mdoc)

Signed-off-by: Alexandre Terrasa <alexandre@moz-code.org>

### CODE REVIEW

**Comment by Morriar** [comment]
test this please

**Comment by privat** [comment]
+1
you should update test_model_visitor_args_2
http://gresil.org/jenkins/job/CI_github/4435/testReport/junit/tests.nitcs.src/test_model_visitor/__test_model_visitor_args_2/

**Comment by jcbrinfo** [comment]
+1

**Comment by Morriar** [comment]
Reroll with test fix

**Comment by Morriar** [comment]
test this please

**Pull request merged**
