### PR TITLE
lib/serialization: fix deserialization constructor calling the default init

### PR DESCRIPTION
**Pull request by xymus**
Restore previous behavior of the deserialization init which should not call the default init. This caused problems on default inits that accessed not yet deserialized attributes.

This also fixes WBTW troubles with game saving and multiplayer.

### CODE REVIEW

**Comment by privat** [comment]
+1. Maybe this solve also the bugs of @Morriar with deserialization

**Comment by privat** [comment]
Some tests failed with `nitc --erasure`: http://gresil.org/jenkins/view/Int%C3%A9gration/job/nit_tests/engine=nitg-e,label=tolkien/1044/testReport/

**Comment by Morriar** [comment]
@privat Yup it solves the problem.

+1

**Comment by xymus** [comment]
The change of behavior was caused by #1566, which also updated a few serialization tests to the broken behavior. Because nitce is not supported by `nitserial`, these tests were expected to fail partially (as in produce empty instances but not crash). However with the broken behavior, the default init was called and filled the instances with the default values and then it tried to deserialize it.

**Comment by privat** [comment]
still one error

**Pull request merged**
