### PR TITLE
nitdoc: display UML class diagram in mmodule pages

### PR DESCRIPTION
**Pull request by Morriar**
Jenkins in busy with CI-nitdoc for now with PRs #1447 and #1446. The demo will have to wait.

Démo is up. Un example of diagram can be found in the burger menu of the dependencies graph: [stdlib](http://moz-code.org/demos/nitdoc-uml/stdlib/module_standard__collection__array.html)

Do not consider commits before 32d81a1 since they are from #1446.

### CODE REVIEW

**Comment by privat** [comment]
I'm waiting for the demo before plussing :)

**Comment by R4PaSs** [comment]
Having seen the demo, this looks cool :)

Nothing strange on the code for my part so, :shipit: !

**Comment by privat** [comment]
the demo! the demo!

**Comment by Morriar** [comment]
can I remove the demo from #1447 then?

**Comment by privat** [comment]
as you wish

**Comment by Morriar** [comment]
There is only one CI-nitdoc and 4 PRs that depend on it for the demo. Pick your favorite :)

**Comment by Morriar** [comment]
Démo is up. Un example of diagram can be found in the burger menu of the dependencies graph: [stdlib](http://moz-code.org/demos/nitdoc-uml/stdlib/module_standard__collection__array.html)

**Comment by Morriar** [comment]
Perfs overview (including the gain from #1446 ):

image

**Comment by privat** [comment]
cool. +1

**Comment by Morriar** [comment]
Reroll for tests

**Comment by Morriar** [comment]
test this please

**Comment by privat** [comment]
Does the last reroll fix the infamous nitdocargs5? If no I can fix it during the merge.

**Comment by privat** [comment]
Other point, you broke digraph by out of memory it seems. Search for `run-nit-nitdoc_full bin/nitdoc` in http://gresil.org/jenkins/job/nit_test_tools/738/consoleFull

**Comment by Morriar** [comment]
test this please

**Comment by privat** [comment]
you should resolve conflits before retesting, or else the testing is done on the old head

**Pull request closed without merging**
