### PR TITLE
core: intro BytesWriter and BytesReader

### PR DESCRIPTION
**Pull request by xymus**
Intro the classes `BytesReader` and `BytesWriter` to support byte read/writer operations directly on `Bytes` in memory.

The new classes are now super classes to `StringReader` (converting the `String` source to `Bytes` in the constructor) and `StringWriter`(cleaning the UTF-8 string in `to_s` only). The only differences between the string and bytes streams are the behavior of `StringWriter::to_s` and the `String` parameter expected by the constructor of `StringReader`.

`BytesWriter` supports writing any bytes, including composing UTF-8 characters byte by byte, a behavior also useful for `StringWriter`:
~~~
var writer = new BytesWriter

# Write just the character first half
writer.write_byte 0xC2u8
assert writer.to_s == "\\xC2"
assert writer.bytes.to_s == "�"

# Complete the character
writer.write_byte 0xA2u8
assert writer.to_s == "\\xC2\\xA2"
assert writer.bytes.to_s == "¢"
~~~

`BytesReader` also supports reading any bytes, including the bytes composing an UTF-8 character for `StringReader`:

~~~
var reader = new BytesReader(b"a…b")
assert reader.read_char == 'a'
assert reader.read_byte == 0xE2u8 # 1st byte of '…'
assert reader.read_byte == 0x80u8 # 2nd byte of '…'
assert reader.read_char == '�' # Reads the last byte as an invalid char
assert reader.read_all_bytes == b"b"
~~~

### CODE REVIEW

**Comment by xymus** [comment]
test this please

**Comment by xymus** [comment]
Fixed the doc as suggested by @R4PaSs. Thanks for the review by the way!

**Comment by privat** [comment]
9eb5998e9f4b87767ea1844c41a8d1506dbeedfa "stream: intro `BytesWriter` and `BytesReader`" breaks tests with the interpreter.

~~~sh
$cd src
$nitc nit.nit
$cd ../tests
$../src/nit ../src/nitcatalog.nit test_prog --no-git
../lib/core/text/flat.nit:1208,25--37: Runtime error: Uninitialized attribute _items
		init do target_items = target._items
		                       ^
,---- Stack trace -- - -  -
| flat$FlatBufferByteIterator$init (../lib/core/text/flat.nit:1208,25--37)
| flat$FlatBufferByteView$iterator_from (../lib/core/text/flat.nit:1193,41--79)
| abstract_text$StringByteView$iterator (../lib/core/text/abstract_text.nit:1344,31--51)
| bytes$Bytes$append (../lib/core/bytes.nit:415,4--24)
| stream$BytesWriter$write (../lib/core/stream.nit:706,3--24)
| stream$Text$write_to (../lib/core/stream.nit:460,32--49)
| stream$Writable$write_to_string (../lib/core/stream.nit:446,3--18)
| markdown$MarkdownProcessor$read_lines (../lib/markdown/markdown.nit:195,31--51)
| markdown$MarkdownProcessor$process (../lib/markdown/markdown.nit:154,16--32)
| doc_down$MDoc$lines_to_html (../src/doc/doc_down.nit:91,11--49)
| doc_down$MDoc$html_documentation (../src/doc/doc_down.nit:62,53--79)
| nitcatalog$Catalog$generate_page (../src/nitcatalog.nit:246,12--34)
| nitcatalog$Sys$main (../src/nitcatalog.nit:723,2--25)
| kernel$Sys$run (../lib/core/kernel.nit:296,13--16)
`------------------- - -  -
~~~

Can you investigate?

**Comment by xymus** [comment]
Added a commit to protect the access to `_items` on empty flat strings. It may not be ideal but it follows the doc of `_items`: *Might be void in some subclasses, be sure to check if set before using it.*

**Comment by privat** [comment]
before:

~~~
$ time ./nitdoc core -d out
real	0m5,306s
user	0m2,257s
sys	0m0,897s
~~~

after:

~~~
$ time ./nitdoc core -d out
real	0m12,021s
user	0m13,245s
sys	0m1,527s
~~~

something seems off

**Comment by xymus** [comment]
Right, I didn't use the right methods on `Bytes`...

I revamped the `BytesWriter` services `write` (to use `Text::append_to_bytes`), `write_char` and `write_bytes`. This should fix the performance issues. Also improved the performance of `Bytes::append_text` by delegating the work to the optimized implementations in the subclasses of `Text`, and set a minimum capacity to `Bytes` at 16 bytes (the same as in `FlatString`) to avoid extra allocs.

master:
~~~
$ time nitdoc core -d out
real	0m4.016s
user	0m2.068s
sys	0m0.700s
~~~

this branch:
~~~
$ time nitdoc core -d out
real	0m4.013s
user	0m1.996s
sys	0m0.736s
~~~

**Comment by privat** [comment]
Again

~~~
Runtime error: Uninitialized attribute _items (../lib/core/bytes.nit:931)
~~~

with the interpreter :(

**Comment by xymus** [comment]
Argh, it should be fixed (again). The performances look good too, maybe even better than before.

The optimizations made the interpreter use a different path, which needed to be protected too.

**Pull request merged**
