### PR TITLE
CSV Benchmarks

### PR DESCRIPTION
**Pull request by R4PaSs**
This PR introduces a new benchmark script for CSV parsers.

Are tested here:

* Nit CSV Ad-hoc parser
* Go standard parser
* Java Apache Commons CSV parser
* Python - Pandas
* Python - Standard
* Ruby - Standard

Will upload some measurements later but *spoiler alert* Python - Pandas is the fastest on large files, Ruby is the slowest by far, Java is the second slower with a big margin from the rest.
Go/Nit/Python-Standard are almost equivalent.

### CODE REVIEW

**Comment by privat** [comment]
test this please

**Comment by privat** [comment]
license http://gresil.org/jenkins/job/CI_github/4308/testReport/junit/cmd/check/license/

**Comment by R4PaSs** [comment]
Reroll: Added licence to nit files

**Comment by privat** [comment]
* I don't like your bash-fu
* I need a Makefile with `all` and `check`. The last one just checks that the nit part is working (should be fast)
* Current output?

+1

**Comment by R4PaSs** [comment]
Yup, my bash skills are nasty to say the least.

As for current output, we have this:

csv_1ml

For times, we have:

1000000_l.csv:

* Python3 - Pandas : 1.1125 s
* Python2 - Pandas : 1.08 s
* Nit : 2.1125 s
* Go : 3.02 s
* Python3 - Standard : 3.3225 s
* Python2 - Standard : 2.77 s
* Java : 10.2225 s
* Ruby : 67.3175 s

1000000_uni_l.csv:

* Python3 - Pandas : 1.29 s
* Python2 - Pandas : 1.275 s 
* Nit : 3.5525 s
* Go : 3.8 s
* Python3 - Standard : 3.6975 s
* Python2 - Standard : 2.98 s
* Java : 10.5725 s
* Ruby : 71.3775 s

**Comment by ppepos** [comment]
:shipit:

**Pull request merged**
