### PR TITLE
nitpackage: generate and check manpages

### PR DESCRIPTION
**Pull request by Morriar**
This PR adds two new features to nitpackage:

--check-man: check manpages existence and content for packages and executable modules
--gen-man: create manpages for packages and executable modules

As example I added new manpages (91b9839) to `lib/markdown` and `lib/github`.

Please only consider the 6 last commits as the rest belongs to #2652, #2653, #2656, #2657 and #2662.

### CODE REVIEW

**Comment by privat** [comment]
you have some sav to update because of the new option -? in usage outputs

**Comment by privat** [comment]
initial make failed (hint: it's nitmd the culprit)

**Comment by Morriar** [comment]
reroll: added manpages for `github_merge` and `nitiwiki`

**Comment by Morriar** [comment]
test this please

**Pull request merged**
