### PR TITLE
jwrapper: prevent nitls to parse the generated files

### PR DESCRIPTION
**Pull request by xymus**
Prevent nitls to parse the generated files by adding an empty `packages.ini` file to the examples folder. This slowed down calls to `make` as nitls is used to detect the dependancies of Nit programs and it took a while to parse the huge generated files.

### CODE REVIEW

**Comment by privat** [comment]
+1

**Comment by BlackMinou** [comment]
+1

**Comment by ppepos** [comment]
+1 ?

**Comment by R4PaSs** [comment]
:ship: :it:

**Pull request merged**
