### PR TITLE
Nitcorn PUT

### PR DESCRIPTION
**Pull request by Morriar**
This PR does two things:

* The first, maybe controversial, but I removed the warning printed by nitcorn on bad post format. The reason is, I am posting a lot of raw json object to my APIs (like github and other APIs work) and I'm getting this warning a lot.

The right thing to do should be to check the format depending on the request type. But the code seem old, I'm not sure I want to rewrite it.

* Second thing: parsing body when receiving PUT requests.

Review: @xymus

### CODE REVIEW

**Comment by privat** [comment]
+1 on the OO part of the code :p

**Comment by jpcaissy** [comment]
👍

**Comment by privat** [comment]
ping @xymus

**Comment by xymus** [comment]
+1

**Comment by xymus** [comment]
All the post format errors that you got... were they invalid requests or in a format unsupported by nitcorn?

**Pull request merged**
