### PR TITLE
lib/popcorn: introduce AuthHandler to check user session

### PR DESCRIPTION
**Pull request by Morriar**
### AuthHandler allows access to session user

 Inherit this handler to access to session user from your custom handler.

 For example, you need a profile handler that checks if the user is logged
 before returning it in json format.
 ~~~nit
 import popcorn::pop_auth

 class ProfileHandler
	super AuthHandler

	redef fun get(req, res) do
		var user = check_session_user(req, res)
		if user == null then return
		res.json user.json
	end
 end
 ~~~

 By using `check_session_user`, we delegate to the `AuthHandler` the responsability
 to set the HTTP 403 error.
 We then check is the user is not null before pursuing.

Signed-off-by: Alexandre Terrasa <alexandre@moz-code.org>

### CODE REVIEW

**Comment by privat** [comment]
Why a new class? Can you just refine `Handler` to add the two new methods so they are accessible to existing classes?

**Comment by Morriar** [comment]
Because I use the `super AuthHandler` to know about what my Handler is.

For exemple:

~~~
class PlayerTrophy
    super AuthHandler # will need an authorized user from session
    super TrophyHandler # will need `/:trophy` in the route

    # ...
end
~~~

**Comment by privat** [comment]
as you wish... +1

**Comment by jcbrinfo** [comment]
:+1:

**Pull request merged**
