### PR TITLE
nitweb: add misc features

### PR DESCRIPTION
**Pull request by Morriar**
A little of everything in this PR:

* show all properties of a class: http://nitweb.moz-code.org/class/core::Array (see all props tab)
* show code into linearization card: http://nitweb.moz-code.org/class/core::Array (see linearization tab)
* show class definitions for modules: http://nitweb.moz-code.org/module/core::array

### CODE REVIEW

**Comment by privat** [comment]
+1

**Comment by privat** [comment]
Loading all the code of all refinements of a class might not be the best idea

eg http://nitweb.moz-code.org/class/core::Sys

**Comment by Morriar** [comment]
Code is only loaded when you click the code icon.

**Comment by jcbrinfo** [comment]
Having the path as a link that does nothing is misleading. Before you told about the icon, I tried to get the code by clicking to the path. Also, for me, the icon looks like a decoration, not a button. Futhermore, being at the far right of the screen, it is barely noticeable on a wide monitor IMHO.

**Pull request merged**
