### PR TITLE
nitrpg: misc fixes

### PR DESCRIPTION
**Pull request by Morriar**
Many fixes for NitRPG in prepatation for the next PR wich introduces the use of MongoDB.

### CODE REVIEW

**Comment by privat** [comment]
+1

**Comment by privat** [comment]
but there is errors: http://gresil.org/jenkins/job/CI_github/3646/

**Comment by R4PaSs** [comment]
:shipit: once tests are fixed

**Comment by privat** [comment]
ping about errors

**Comment by Morriar** [comment]
test this please

**Pull request merged**
