### PR TITLE
nitweb: use index for quick search

### PR DESCRIPTION
**Pull request by Morriar**
This PR use the `model_index` API to provide better quicksearch in nitweb.

Demo: http://nitweb.moz-code.org/

Will maybe close a shitstorm of quicksearch related issues but I'm to lazy to check the numbers...

### CODE REVIEW

**Comment by Morriar** [comment]
Also the four first commits are from #2304

**Comment by Morriar** [comment]
+1

**Comment by R4PaSs** [comment]
+!

**Comment by jcbrinfo** [comment]
+1

**Comment by jcbrinfo** [comment]
When I mispell a name, it is so lightning fast now compared to the old index.

**Pull request merged**
