### PR TITLE
Opportunity: intro ∇ ratio

### PR DESCRIPTION
**Pull request by xymus**
Add the ∇ ratio to Opportunity with a customizable multiplier. It assigns weight to the choices of participants so that someone who select all possible answers puts less weight on each answer, and someone who choses a single answer puts her full weight on it.

It can be used to count the number of pizzas to order (with a multiplier of 0.4) and to give more importances to the available times of busy people when scheduling a meeting.

### CODE REVIEW

**Comment by privat** [comment]
+1

**Comment by privat** [comment]
what about *maybe* (?) options? how are they counted in the ∇ ratio?

**Comment by xymus** [comment]
Maybe options counts as half a check option.

**Comment by R4PaSs** [comment]
As much as I would have loved to have a real pizza slice character, :shipit: !

**Pull request merged**
