### PR TITLE
Fix Opportunity behavior with unicode characters

### LINKED ISSUE #1695: Opportunity UTF8 issue
Texts from the user-input fields that are rendered as garbage with unicode.

### PR DESCRIPTION
**Pull request by xymus**
Fix #1695. It is already deployed on http://xymus.net/opportunity/ (Take a look at http://xymus.net/opportunity/?meetup_id=B962ECD89E0AE40FF888569AE8D816B36F128E10)

### CODE REVIEW

**Comment by privat** [comment]
You mangeled `Aléxis` because you cannot find a non-ascii character in `Alexis Laferrière`?

**Comment by privat** [comment]
+1

**Comment by R4PaSs** [comment]
:shipit:

**Comment by xymus** [comment]
@privat, I was too lazy to write my last name...

**Comment by xymus** [comment]
Rerolled with a better implementation of to_percent_encoding.

**Pull request merged**
