### PR TITLE
examples/fibonacci: fix off-by-one fibonacci

### PR DESCRIPTION
**Pull request by tonygaetani**
Signed-off-by: Tony Gaetani <tony.gaetani@gmail.com>

### CODE REVIEW

**Comment by tonygaetani** [comment]
Related: https://github.com/nitlang/nit/pull/2130
Related: https://nitlanguage.org/manual/class.html#Class_Refinement

**Comment by privat** [comment]
+1
ok toaster: ok to test

**Comment by jcbrinfo** [comment]
:+1:

**Comment by jcbrinfo** [comment]
Please insert this line after line 32 of the `NOTICE` file:
~~~
         2016      Tony Gaetani <tony.gaetani@gmail.com>
~~~
Thank you.

**Comment by xymus** [comment]
It's not necessary to update the notice file, we can handle that.

Thank you for the fix!

**Comment by jcbrinfo** [comment]
> It's not necessary to update the notice file, we can handle that.

Done. (#2135)

**Pull request merged**
