### PR TITLE
Nitweb snippets

### PR DESCRIPTION
**Pull request by Morriar**
Documentation of this PR is [here](http://nitweb.moz-code.org/docdown?snippet=IyBIZWxsbyBHaXRodWIKClRoaXMgaXMgYSBkb2N1bWVudGF0aW9uIHNuaXBwZXQuCllvdSBjYW4gdXNlIGl0IHRvIGRvY3VtZW50IHRoaW5ncyBvbiB0aGUgZmx5IGFuZCBzaGFyZSBpdCB3aXRoIG90aGVyIE5pdCB1c2Vycy4KCiMjIEJhc2ljcwoKQmFzaWNhbGx5LCBEb2Nkb3duIGFsbG93cyB5b3UgdG8gd3JpdGUgbWFyZG93biBkb2N1bWVudGF0aW9uIHVzaW5nIHRoZSBbbWFya2Rvd25dKGh0dHBzOi8vZGFyaW5nZmlyZWJhbGwubmV0L3Byb2plY3RzL21hcmtkb3duLykgZm9ybWF0LgoKU29tZSBleGFtcGxlczoKCn5%2BfnJhdwoqIHRoaXMKKiBpcyBhCiogbGlzdAp%2Bfn4KCj4gVGhpcyBpcyBhIGNpdGF0aW9uLgoKIyMgV3JpdGluZyBuaXQgY29kZQoKRG9jZG93biBkZXBlbmRzIG9uIHRoZSBuaXQgaGlnaGxpZ2h0ZXIgc28geW91IGNhbiB3cml0ZSBOaXQgd2l0aGluIHlvdXIgZG9jIHNuaXBwZXQ6Cgp%2Bfn4KcHJpbnQgImhlbGxvIHdvcmxkIgp%2Bfn4KCiMjIExpbmtpbmcgbW9kZWwgZW50aXRpZXMKCkRvY2Rvd24gdXNlcyBgW1t3aWtpbGlua3NdXWAgdG8gZW5oYW5jZSB0aGUgbWFya2Rvd24gbGFuZ3VhZ2UgZm9yIGRvY3VtZW50YXRpb24uCgpVc2luZyB3aWtpbGlua3MgeW91IGNhbiBjcmVhdGUgbGlua3MgdG8gdGhlIGRvY3VtZW50YXRpb24gb2YgYSBNRW50aXR5IGxpa2UgdGhpczogW1tjb3JlOjpBcnJheV1dCllvdSBjYW4gbGluayB0byBtZW50aXRpZXMgbGlrZSB0aGlzOiBbW2NvcmVdXS4KClRoZSBgZG9jYCBjb21tYW5kIGluamVjdHMgdGhlIGRvY3VtZW50YXRpb24gb2YgYSBNRW50aXR5IGludG8gdGhlIHNuaXBwZXQ6Cgp%2Bfn4KW1tkb2M6IGNvcmU6OkFycmF5XV0Kfn5%2BCgpFeGFtcGxlIHdpdGggdGhlIFtbY29yZTo6QXJyYXldXSBjbGFzczoKW1tkb2M6IGNvcmU6OkFycmF5XV0KCiMjIExpc3RzCgpUaGUgYGxpc3RgIGNvbW1hbmQgaXMgdXNlZCB0byBpbmplY3QgbWVudGl0aWVzIGxpc3RzIGludG8gYSBzbmlwcGV0czoKCiAgICBbW2xpc3Q6IGNvcmU6OmFycmF5XV0KCkV4YW1wbGUgd2l0aCB0aGUgY2xhc3NlcyBpbnRvIHRoZSBbW2NvcmU6OmFycmF5XV0gbW9kdWxlOgpbW2xpc3Q6IGNvcmU6OmFycmF5XV0KCiMjIEluamVjdGluZyBjb2RlCgpVc2UgdGhlIGBjb2RlYCBjb21tYW5kIHRvIGludHJvZHVjZSBhIGNvZGUgc25pcHBldCBpbnRvIHlvdXIgZG9jdW1lbnRhdGlvbjoKCiAgICBbW2NvZGU6IGNvcmU6OkFycmF5Ojpmcm9tXV0KCkV4YW1wbGU6CltbY29kZTogY29yZTo6QXJyYXk6OmZyb21dXQoKIyMgR3JhcGgKCkZpbmFsbHksIHRoZSBgZ3JhcGhgIGNvbW1hbmQgY2FuIGJlIHVzZWQgdG8gaW5zZXJ0IGEgU1ZHIGdyYXBoIGFib3V0IGEgbWVudGl0eS4KCiAgICBbW2dyYXBoOiBjb3JlOjpjb2xsZWN0aW9uXV0KCkV4YW1wbGU6CgpbW2dyYXBoOiBjb3JlOjpjb2xsZWN0aW9uXV0KCiMjIEVycm9ycyBhbmQgd2FybmluZ3MKCk5pdHdlYiB3aWxsIGNoZWNrIHlvdXIgc25pcHBldCBmb3IgaW5jb25zaXN0ZW5jaWVzLgoKSXQgaXMgYWJsZSB0byBsb2NhdGUgdW5rbm93biBjb21tYW5kczoKCn5%2BfnJhdwpbW2xvbDogbG9sXV0Kfn5%2BCgpbW2xvbDogbG9sXV0KClVua25vd24gZW50aXRpZXM6Cgp%2Bfn5yYXcKW1tkb2M6IGxvbF1dCn5%2BfgoKW1tkb2M6IGxvbF1dCgpBbmQgZXZlbiB3YXJuIHlvdSB3aGVuIGluY2x1ZGluZyBlbXB0eSBkb2N1bWVudGF0aW9uOgoKfn5%2BcmF3CltbZG9jOiBjb3JlJENvbXBhcmFibGUkT2JqZWN0OjpTRUxGXV0Kfn5%2BCgpbW2RvYzogY29yZSRDb21wYXJhYmxlJE9iamVjdDo6U0VMRl1d).

PS: Review only the last 3 commits, others are from #2193.

### CODE REVIEW

**Comment by privat** [comment]
How could this PR have merge conflicts?

**Comment by privat** [comment]
How my god. This is fun

**Comment by jcbrinfo** [comment]
May be cool to use as a scratchpad to preview how one’s documentation renders with Docdown.

However, at soon as a type a non-ASCII character, everything brakes.

**Comment by privat** [comment]
+1

**Pull request merged**
