### PR TITLE
examples/fibonacci: fix fibonacci function

### PR DESCRIPTION
**Pull request by tonygaetani**
In the fibonacci example, all values were off by one because the first element of the fibonacci sequence is 0, not 1. Now the fibonacci example also includes and example usage of `else if`.

### CODE REVIEW

**Comment by privat** [comment]
thanks.
jenkins: ok to test

**Comment by jcbrinfo** [comment]
Related: https://nitlanguage.org/manual/class.html#Class_Refinement

**Comment by jcbrinfo** [comment]
:+1: +1

**Comment by Morriar** [comment]
Hi @tonygaetani,

We require all our commits to mention the signed-off tag, can you rebase to add `Signed-off-by: Tony Gaetani <tony.gaetani@gmail.com>` in your commit?

Thanks a lot!

**Comment by tonygaetani** [comment]
@Morriar okay done

**Comment by tonygaetani** [comment]
Wait sec, the one from the docs is correct and more concise.

https://nitlanguage.org/manual/class.html#Class_Refinement

I'll close this one and submit a new PR.

**Pull request closed without merging**
