### PR TITLE
model: Fix minor documentation mistakes

### PR DESCRIPTION
**Pull request by jcbrinfo**
Signed-off-by: Jean-Christophe Beaupré <jcbrinfo@users.noreply.github.com>

### CODE REVIEW

**Comment by privat** [comment]
Coud you please have the author name matching the Signed-off-by name? i.e. "Jean-Christophe Beaupré" in both? c.f. http://gresil.org/jenkins/job/CI_github/4607/testReport/junit/cmd/check/signed_off_by/

**Comment by privat** [comment]
+1

**Comment by jcbrinfo** [comment]
If I understand well, I can not submit quickfixes trough GitHub (because it always use my user name as the author). :disappointed:

**Comment by privat** [comment]
oh... then OK. no need to worry. quickfixes are good. I will try to make my check script more lenient.

**Comment by jcbrinfo** [comment]
I’m writting a script that will re-author my commits…

**Comment by jcbrinfo** [comment]
:recycle: [`stash, pull, checkout, amend, push, checkout, stash pop`](https://gist.github.com/jcbrinfo/1b14520ccf28352c2f0f285b2f3e679d)

**Comment by jcbrinfo** [comment]
[Script available on Gist.](https://gist.github.com/jcbrinfo/1b14520ccf28352c2f0f285b2f3e679d)

**Pull request merged**
