### PR TITLE
modelize_property: Promote `refine-type` to an error

### PR DESCRIPTION
**Pull request by jcbrinfo**
Signed-off-by: Jean-Christophe Beaupré <jcbrinfo@users.noreply.github.com>

### CODE REVIEW

**Comment by privat** [comment]
If I recall correctly, the old mnit is abusing this (and the origin of the false-error). Did you try do compile and execute mnit_dino for instance?

**Comment by jcbrinfo** [comment]
Not on my computer (because of dependencies). But, Jenkins did: http://gresil.org/jenkins/job/CI_github/4762/testReport/cmd/mnit_dino/make/

**Comment by privat** [comment]
Seems OK then. Good riddance!
+1

**Comment by privat** [comment]
Maybe wait about @xymus or @Morriar as they might use that in some of their home projects.

**Comment by jcbrinfo** [comment]
I run a search to be sure (`find . -iname '*.nit' -exec grep -Pazl 'redef( extern| abstract)? (interface|class)[^\n]*(\n\t[^\n]*)*redef type' '{}' +`). Excluding tests, I only find the following 2 cases (that are not actually virtual type refinements and don’t trigger the error):
* Addition of a superclass immediatly followed by the overriding of a virtual type of this superclass. Example: `redef class A super Comparable; redef type OTHER: A…`
* In the same module, introduction of a virtual type in a superclass, then overriding of this virtual type in all subclasses. Example: `APropDef::MPROPDEF` in `modelize_class`

**Pull request merged**
