### PR TITLE
nitweb: render wikilinks

### PR DESCRIPTION
**Pull request by Morriar**
This PR allows nitweb to render wikilinks from README.md files.

Here the demo with the lib/core/README.md file: http://nitweb.moz-code.org/doc/core

### CODE REVIEW

**Comment by privat** [comment]
so nice PR +1

**Comment by jcbrinfo** [comment]
+1

**Comment by jcbrinfo** [comment]
If you want to make your fan spin at maximum speed and freeze your web browser: http://nitweb.moz-code.org/doc/core::Sys
:smile:

**Comment by Morriar** [comment]
@jcbrinfo good catch but not related to this PR,

see: http://nitweb.nitlanguage.org/doc/core::Sys

**Pull request merged**
