### PR TITLE
nitls: fix tree representation of nested groups

### PR DESCRIPTION
**Pull request by privat**
nitls wrongly detached some nested groups in tree-mode.

Before:

~~~
$ nitls -tp lib/nitcorn/examples/src/nitcorn_hello_world.nit lib/nitcorn/http_response.nit
lib/nitcorn/examples
`--lib/nitcorn/examples/src
   `--lib/nitcorn/examples/src/nitcorn_hello_world.nit
lib/nitcorn
`--lib/nitcorn/http_response.nit
~~~

After:

~~~
$ nitls -tp lib/nitcorn/examples/src/nitcorn_hello_world.nit lib/nitcorn/http_response.nit
lib/nitcorn
|--lib/nitcorn/examples
|  `--lib/nitcorn/examples/src
|     `--lib/nitcorn/examples/src/nitcorn_hello_world.nit
`--lib/nitcorn/http_response.nit
~~~

### CODE REVIEW

**Comment by xymus** [comment]
+1

**Comment by jcbrinfo** [comment]
:+1: +1

**Comment by privat** [comment]
ping @Morriar

**Comment by Morriar** [comment]
+1

**Pull request merged**
