### PR TITLE
nitunit: import frontend

### PR DESCRIPTION
**Pull request by Morriar**
So the tests can use annotations and other things introduced in compiler phases.

Signed-off-by: Alexandre Terrasa <alexandre@moz-code.org>

### CODE REVIEW

**Comment by privat** [comment]
+1

**Comment by privat** [comment]
I do not know why but this cause issues with some tests of nitunit http://gresil.org/jenkins/job/CI_github/4751/testReport/

**Comment by Morriar** [comment]
Reroll: the default `Toolcontext` used by nitunit was not `keep_going` so the tests stopped at the first error.

Using keep going allows nitunit to spot more compilation errors as can be seen in the update for the test files: https://github.com/nitlang/nit/pull/2283/commits/810dde41aa6df59443b897829a56dabd2215fe3d#diff-07f589fe33d5b380a6fafb464c2b7885R1

**Comment by privat** [comment]
+1

**Comment by jcbrinfo** [comment]
So much for a single line of code. :wink: 

:shipit: +1

**Pull request merged**
