### PR TITLE
Beefup check contrib

### PR DESCRIPTION
**Pull request by privat**
This change make the caller pass the additional `make` rules to execute. So now `check` or `android` can be given to mass build projects that expose such rules.

### CODE REVIEW

**Comment by privat** [comment]
Note, this PR is made from my own fork of nit. I did some ugly and risky shenanigans to keep existing redirection of <https://github.com/privat/nit> (due to the transfer) while having a fork (named mynit). Using the button `fork` was a no-no since it would have destroyed the redirection.

**Comment by privat** [comment]
reroll: fix some things in lib that where not up to the standard and that the PR doscovered

**Comment by Morriar** [comment]
+1

**Comment by R4PaSs** [comment]
:shipit:

**Pull request merged**
