### PR TITLE
nitiwiki: external highlighter

### PR DESCRIPTION
**Pull request by privat**
This is a cleaned up version of what is currently doing the code highlighting and the table in the deployed http://nitlanguage.org

The basic idea here is to delegate the job to some other program. The program has to be configured in the config.ini under the key `wiki.highlighter`

This approach, while not pure nit, makes it quite easy to use whatever highlighter program the user prefer with whatever options (instead of hard-coding a specific external program in the nit source code).

An advanced way is to delegate to a shell script that checks arguments then dispatches to a real program.

ping maintainer: @Morriar

### CODE REVIEW

**Comment by privat** [comment]
Reroll: in fact I greatly improved and documented the thing and make it more robust, versatile and easy to use. Since I assume that nobody did read the first version, I wont detail the change.

**Comment by R4PaSs** [comment]
You assume correctly for my part, so far though I can't see much done wrong here, so here's my :shipit:

**Comment by privat** [comment]
Here a demo for nitlanguage http://info.uqam.ca/~privat/nitlanguage/
The config used is nitlang/nitlanguage#4

**Comment by privat** [comment]
reroll: fix some spelling, and add a commit to solve tests (I hope)

**Pull request merged**
