### PR TITLE
nitweb: show mentities details

### PR DESCRIPTION
**Pull request by Morriar**
Add more content to mentities pages.

Packages list inner groups
* http://nitweb.moz-code.org/package/core

Groups show parent and list inner groups/modules
* http://nitweb.moz-code.org/group/core%3E
* http://nitweb.moz-code.org/group/core%3Ecollection%3E

Modules show imported modules, introduced classes and redefinitions
* http://nitweb.moz-code.org/module/core::array

Classes show super classes, introduced properties, redefined properties
* http://nitweb.moz-code.org/class/core::Array

Bonus, all lists are filterable by raw string or visibility.

### CODE REVIEW

**Comment by privat** [comment]
Very cool.

By the way, http://nitweb.moz-code.org/property/core::Object::SELF is very long to load because http://nitweb.moz-code.org/api/entity/core::Object::SELF is 12MB of JSON (c.f. #1563)

**Comment by privat** [comment]
+1

**Comment by Morriar** [comment]
Reroll: fixed whitespaces in html

**Comment by Morriar** [comment]
@privat I have no out of the box solution for `SELF`.

Maybe mark all redefs as `is_fictive` but we still want the redef information for every type in the documentation.

One quick, but no so good, solution would be to create a special rule for SELF.
One other way to relieve the browser/server stress would be to paginate the results and load pages as you scroll down.

**Comment by privat** [comment]
SELF is special, but `http://nitweb.moz-code.org/api/entity/core::abstract_text::Object::to_s` is still 250KB

**Pull request merged**
