### PR TITLE
nitweb: encode URIs

### LINKED ISSUE #2164: Nitweb does not percent-encode metacharacters in URIs
According to RFC 3986, only unreserved character should be left unescaped in URIs (see http://tools.ietf.org/html/rfc3986#section-2.3). However, Nitweb produces links with URIs like `http://nitweb.moz-code.org/property/core::Int::%` (for the modulo operator of `Int`). Furthermore, the URI http://nitweb.moz-code.org/property/core%3A%3AInt%3A%3A%25 points to an empty page.

Note: Most web browsers display URIs as unescaped as possible  in the address bar (for example, both Firefox and Chrome display `http://nitweb.moz-code.org/property/core%3A%3AInt%3A%3A%25` as `http://nitweb.moz-code.org/property/core::Int::%25`). So, legibility is not a valid counter-argument to proper percent-escaping.

### PR DESCRIPTION
**Pull request by Morriar**
Closes #2164

Signed-off-by: Alexandre Terrasa <alexandre@moz-code.org>

### CODE REVIEW

**Comment by Morriar** [comment]
test this please

**Comment by Morriar** [comment]
Reroll: removed useless `window` prefix

**Comment by jcbrinfo** [comment]
I see 2 cases :
* If `web_url` is a full URI or a path, your code is wrong because it can’t distinguish (for example) the component separator (`/`) from a `/` inside a component. A string can’t be an URI if the reserved characters are left unencoded (else, the language would be ambiguous). So, if you must percent-encode it, `web_url` can’t be a valid URL.
* If `web_url` is an URI component, the name of this attribute is misleading.

**Comment by jcbrinfo** [comment]
Here is a concrete example: `core::Numeric::/`, as an URI component, is `core%3A%3ANumeric%3A%3A%2F`, so we can write URIs such as `http://nitweb.moz-code.org/doc/core%3A%3ANumeric%3A%3A%2F`. However, if you percent-encode `http://nitweb.moz-code.org/doc/core::Numeric::/`, you will get the URI component `http%3A%2F%2Fnitweb.moz-code.org%2Fdoc%2Fcore%3A%3ANumeric%3A%3A%2F`

**Pull request merged**
