### PR TITLE
math: Intro `Comparable::clamp`

### PR DESCRIPTION
**Pull request by xymus**
The `clamp` service restricts a value within a given range. It is a common service in GLSL and it is especially useful for games. Even though the alternative is short: `x = x.min(1.0).max(0.0)`, it is quite confusing and the simple `x = x.clamp(0.0, 1.0)` is easier to read.

### CODE REVIEW

**Comment by jcbrinfo** [comment]
Why not put it in `Comparable`? This where `min` and `max` are introduced.

**Comment by privat** [comment]
toaster: test this please

**Comment by xymus** [comment]
Rerolled to fix tests and move it up to Comparable, updating the description.

**Comment by jcbrinfo** [comment]
:+1: +1

**Comment by R4PaSs** [comment]
:shipit:

**Pull request merged**
