### PR TITLE
Intro support for async HTTP requests and ListLayout for iOS

### PR DESCRIPTION
**Pull request by xymus**
This PR completes the implementation app::UI for iOS by implementing `ListLayout` using a `UITableView`. It also introduces the implementation of `http_request` using services from the foundation framework. 

These features enable the Tnitter portable application to be compiled for iOS without modification.

The remaining API of app.nit still missing on IOS are `data_store`, `audio` and maybe `assets`.  At this point, only `data_store` is required for fully featured portable applications using the native UI.

---

As with #1942, some generated code has been commented so it can be reactivated when useful and when the needed types are also wrapped.

### CODE REVIEW

**Comment by xymus** [comment]
test osx please

**Comment by privat** [comment]
+1

**Comment by xymus** [comment]
test this please

**Comment by xymus** [comment]
test osx please

**Comment by xymus** [comment]
The Android errors are expected until #1944 is merged, and the 2 remaining error on OS X are caused by unresolved dependencies.

http://gresil.org/jenkins/job/CI_github/4039

**Pull request merged**
