### PR TITLE
Relocate examples

### PR DESCRIPTION
**Pull request by privat**
Some short programs in `examples` are related to specific libraries. Therefore to improve coupling and cohesion, these examples are moved into a subdirectory of their associated libs.

Basically, it means moving `examples/foo` into `lib/foo/examples`

### CODE REVIEW

**Comment by xymus** [comment]
For xymus_net errors. It requires -I the src folder from most nitcorn projets, so it couldn't be tested with tests.sh. But, if I'm not mistaken, we can import from contrib now? So would it work to update the imports to something like `import opportunity::opportunity_controller`?

**Comment by privat** [comment]
@xymus in fact, the res file leaks absolute filepaths (the diff is about `/home/privat` vs `/home/jenkins`).
This is a loader bug and is solved by #1654. I can wait that this one is merged.

For the `opportunity::opportunity_controller` there is still an issue for some projects (related to #1265 in fact), this is something I planned to solve once #1654 (again) is merged.

**Comment by privat** [comment]
reroll: fix whitespace before moving files and mark the xymus test as UNDEFINED

**Comment by R4PaSs** [comment]
:shipit: once the conflit has been resolved

**Comment by privat** [comment]
rebase with #1654 (for the xymus issue) and also skip `lib/android/examples/src/ui_test.nit` on some platforms/engines since all examples from lib are now tested

**Comment by privat** [comment]
rereroll: rebase again with #1654 (that was badly done) and isolate the currently broken `xymus_net.nit` that broke nitdoc for the lib

**Comment by xymus** [comment]
+1

**Comment by privat** [comment]
reroll: just remove the relocation of `examples/nitcorn`. I finally prefer to solve the loader issue instead of introducing hack to revert latter

**Pull request merged**
