### PR TITLE
Bench strings

### PR DESCRIPTION
**Pull request by R4PaSs**
Update for existing benches since standard was renamed to core and a few PRs have modified the code.

Also added new variant with buffered NativeStrings.

### CODE REVIEW

**Comment by privat** [comment]
I should add the test in the big tests to spot regressions

**Comment by privat** [comment]
+1

**Comment by R4PaSs** [comment]
Reroll: tests should not fail anymore

**Comment by privat** [comment]
I merged an old version 0eb90f31eb2a060290af00b1b21b112e35443748, I'm not sure how this occured.
Please rebase and solve the conflict so I can remerge a fixed version.

**Comment by R4PaSs** [comment]
Ok, conflict has been solved, tested on my machine for a few benches (not all, ain't nobody got time for that), this should be working now.

**Comment by privat** [comment]
bizarre, ca passe pas: http://gresil.org/jenkins/job/nit_test_tools/844/testReport/cmd/bench/strings/

**Pull request closed without merging**
