### PR TITLE
typing: include a hook to enable more precise error information on 'expected expression' errors

### PR DESCRIPTION
**Pull request by privat**
The point is to help to solve the second part of #1392

Before:

~~~
print (-1).to_s
^
test.nit:2,1--10: Error: expected an expression.
~~~

After:

~~~
print (-1).to_s
^
test.nit:2,1--10: Error: expected an expression to be the receiver of `to_s`
~~~

### CODE REVIEW

**Comment by xymus** [comment]
In this precise example, the new error message doesn't help much.

But it's still an overall improvement so +1

**Comment by privat** [comment]
@xymus do you have a better proposal?

**Comment by xymus** [comment]
Well... if possible, adding the actual receiver at the end would help a bit:
~~~
test.nit:2,1--10: Error: expected an expression as the receiver of `to_s` instead of `print (-1)`.
~~~

**Comment by privat** [comment]
the actual receiver is in red in fact. I can improve with additional carrets:

~~~
print (-1).to_s
^^^^^^^^^^
test.nit:2,1--10: Error: expected an expression to be the receiver of `to_s`
~~~

**Pull request merged**
