### PR TITLE
nitmetrics: add more metrics and some cleaning

### PR DESCRIPTION
**Pull request by Morriar**

### CODE REVIEW

**Comment by Morriar** [comment]
Reroll, fixed .sav

**Comment by privat** [comment]
some errors http://gresil.org/jenkins/job/CI_github/5105/testReport/junit/cmd/nit/errors/

**Comment by Morriar** [comment]
test this please

**Comment by privat** [comment]
TMP is bad and you should feel bad

**Comment by Morriar** [comment]
I didn't even said that it was a reroll yet. Do I look into your unfinished
stuff? Leave this poor code alone!

**Pull request closed without merging**
